// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcrHh-3zo9SD05GCEJU6RqDGk6_duGHMA',
    appId: '1:1096895368613:web:3cb585b2e46f90b06c6c4c',
    messagingSenderId: '1096895368613',
    projectId: 'mywallet-78fb6',
    authDomain: 'mywallet-78fb6.firebaseapp.com',
    storageBucket: 'mywallet-78fb6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8uP9IJk2Pb3j5RLMhIep5I2bhkXbKxA',
    appId: '1:1096895368613:android:723d4e45698f487c6c6c4c',
    messagingSenderId: '1096895368613',
    projectId: 'mywallet-78fb6',
    storageBucket: 'mywallet-78fb6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8MWge30bd9pzOSDu51-5byqWHu1JBi78',
    appId: '1:1096895368613:ios:026c11e36d730bce6c6c4c',
    messagingSenderId: '1096895368613',
    projectId: 'mywallet-78fb6',
    storageBucket: 'mywallet-78fb6.firebasestorage.app',
    iosBundleId: 'com.example.myPocketWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcrHh-3zo9SD05GCEJU6RqDGk6_duGHMA',
    appId: '1:1096895368613:web:8d171bac69e802536c6c4c',
    messagingSenderId: '1096895368613',
    projectId: 'mywallet-78fb6',
    authDomain: 'mywallet-78fb6.firebaseapp.com',
    storageBucket: 'mywallet-78fb6.firebasestorage.app',
  );

}